import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import QueryProvider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NavItem = ({ children }: { children: React.ReactNode }) => {
  let url = children?.toString().toLowerCase();
  let filteredUrl = url === "main" ? "" : url;
  return (
    <Link href={`/${filteredUrl}`}>
      <p className="cursor-pointer">{children}</p>
    </Link>
  );
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-20 justify-center mt-10">
          <NavItem>About</NavItem>
          <NavItem>Main</NavItem>
          <NavItem>TodoSSR</NavItem>
          <NavItem>TodoCSR</NavItem>
        </nav>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
